name: separate-trees 
channels:
  - conda-forge
  - defaults
dependencies:
  - coverage
  - cryptography
  - future
  - gdown
  - gdal
  - geopandas
  - matplotlib
  - numpy
  - libiconv
  - python
  - scikit-image
  - scikit-learn
  - tqdm
  - pip:
    - ray
    - pcutils
    - opencv-python
    - geopy
    - ipdb
    - pylint
    - pytest
    - python-dateutil
    - rasterio
